### ISSUE TITLE
Turn off the popups when in debug mode

### ISSUE THREAD

**Issue by chrismanderson** [MobileAppTracking/cocoapod#5]
Possible to disable the popups (duplicate request and debug) when in debug mode? We spend most of our time coding the app in debug mode, so having to clear those two popups each time gets old.

**Comment by harshal-hasoffers** [comment]
The debug/allow-dup mode alerts are shown as a precaution to make sure that the app is not released with the incorrect settings enabled. If you wish to disable the alerts, you would need to build a custom build using the latest source code that is publicly hosted at https://github.com/MobileAppTracking/sdk-release.
