### ISSUE TITLE
The Pod is broken, CocoaPods team say

### ISSUE THREAD

**Issue by appmagnetics** [MobileAppTracking/cocoapod#7]
See https://github.com/CocoaPods/CocoaPods/issues/3580

**Comment by harshal-hasoffers** [comment]
Thanks for pointing out the issue. Please try installing the updated pod.

**Comment by appmagnetics** [comment]
Hi, I've tried to use 3.9.2 and  it tells me "MobileAppTracker.h" by compiling. Indeed, after pod install .h files are not visible in pod directory.

**Comment by harshal-hasoffers** [comment]
After I add `pod 'MobileAppTracker'` to the Podfile file and call `pod install`, the project folder structure is modified as follows:
![cocoapod_project](https://cloud.githubusercontent.com/assets/2146296/7821676/3ecadf32-03a5-11e5-8fbf-06bb59676afa.png)

MobileAppTracker can then be imported by calling:
`@import MobileAppTracker;`

If the `@import` doesn't work, can you please try adding the pod to a blank project and see how it works?

**Comment by jstart** [comment]
@harshal-hasoffers Why did you guys decide to go to frameworks?  Doesn't that limit your support to only iOS 8?

**Comment by harshal-hasoffers** [comment]
Framework only provides a directory structure to store the header files and .a lib archive file.
Mere use of frameworks would not affect the supported iOS version. The SDK should still work fine with older iOS versions 5.1.1+.

**Comment by jstart** [comment]
Right at eHarmony we are facing an issue because we need to pull it into a private tracking library pod and embedding a framework inside a static library is causing build failures.  This probably shouldn't have been a point release if you guys are following Semantic versioning, since it significantly changed how we import the framework and we need to use @import instead of #import <

**Comment by harshal-hasoffers** [comment]
Both types of import statements should work fine.
- `#import <MobileAppTracker/MobileAppTracker.h>`
- `@import MobileAppTracker;`

**Comment by appmagnetics** [comment]
Sorry, cannot confirm it's solved. I've spent some hour trying to understand what happens. Project compiles succesfully on one machine and gives me Linker error with MobileAppTracker library on clean install on another machine. Pod versions looked the same. 

Finally I was deinstalling cocoa pods and found out there were several versions of pods on this machine. 
I removed them all and installed 0.35.0. Then the project was finally built without errors!  This was done using 3.9.3 from MAT SDK. 

When I upgrade cocoa pods to 0.37.x, I get the same linker error again.

**Comment by harshal-hasoffers** [comment]
I partly repeated your tests, but my project builds fine even after that.

**Steps:**
- uninstall all versions of Cocoapods
````
sudo gem uninstall cocoapods
sudo gem uninstall cocoapods-core
````
- reinstall latest version of Cocoapods
````
sudo gem install cocoapods
````
- create a single view Xcode iOS project
- create a Podfile in the project root folder with contents -- `pod 'MobileAppTracker'`
- `pod install`
- open xcworkspace
- `#import <MobileAppTracker/MobileAppTracker.h>"` works fine in AppDelegate.h

**Comment by appmagnetics** [comment]
The issue is not with including headers, but the original one - linker error "Library not found". 
What do you need to investigate this issue?

**Comment by appmagnetics** [comment]
![slack-imgs](https://cloud.githubusercontent.com/assets/7034162/8334629/413a3168-1a99-11e5-9151-c76ebd7441f3.jpg)

Here is the screenshot

**Comment by john-gu** [comment]
@appmagnetics Are you encountering this from opening the .xcworkspace file, or .xcodeproj?

**Comment by appmagnetics** [comment]
.xcworkspace

**Comment by harshal-hasoffers** [comment]
@appmagnetics 
- Do you see this error when including MobileAppTracker by itself or only when using it along with other libraries?
- What are your Podfile contents?
- Can you share a sample project that we can use to repro the issue?
If you like you can email support@mobileapptracking.com and we can take this up there.
