### ISSUE TITLE
Error when compiling pod with GCC_WARN_ABOUT_MISSING_NEWLINE

### ISSUE THREAD

**Issue by alkozin** [MobileAppTracking/cocoapod#9]
Can you add new line at the end of all public headers?

![screen shot 2015-06-18 at 11 54 10 pm](https://cloud.githubusercontent.com/assets/2376017/8247069/33c7c3c2-1663-11e5-86c3-e3dfb79af512.jpg)

**Comment by harshal-hasoffers** [comment]
This warning/error can be managed from the Xcode project settings. You can disable it under Project > Build Settings, in section `Apple LLVM 6.1 - Warnings - All Languages` by setting `Missing Newline At End Of File` to `No` .

**Comment by alkozin** [comment]
I'm using this config for my projects: https://github.com/boredzo/Warnings-xcconfig
It helps to avoid bugs.

I added "inhibit_all_warnings!" to Podfile but errors is still appear.
It's your decision to use this config or not, but I think project should be flexible and suits for projects with different settings.

What do you think?

**Comment by harshal-hasoffers** [comment]
We will be including a newline at end-of-file to all the public headers in the next SDK release. For the time being, you can either turn off the warning or manually add a newline to the erring header files.

**Comment by alkozin** [comment]
Thank you!
